{% set version = "2.0.1" %}

package:
  name: mgwr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mgwr/mgwr-{{ version }}.tar.gz
  sha256: e84c991e431cf06b61c25354fcf30ee2b4677fa835f3685775c2c8b05b4a250b

build:
  number: 1000
  # is pure python, uses 2to3, and depends on libpysal that is py3k only!
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libpysal
    - numpy
    - scipy
    - spglm
    - spreg

test:
  imports:
    - mgwr

about:
  home: https://github.com/pysal/mgwr
  license: BSD-3-Clause
  # https://github.com/pysal/mgwr/issues/25
  # license_file: 
  summary: 'Multiscale geographically weighted regression'

extra:
  recipe-maintainers:
    - ocefpaf
