appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RVjFv+/cY5mGP2c5sJnTSESvK2UIdHD6K1Ki0FSwyxbYXkqRx/bpWkPu6Eo3EfB+K2134JhP4e8qmY55MylTFQmcHtiNPHKLRahoLCQLyoAZer4XqXu5Fxge2cAfdXN9XACwyVbEcA964RIvctmSOV1pVKiapXvr1J/Z3xLPlFR6NwVC9wb9DeZix6tM5c40YjjF8h+v3IaqbXAu5o5ftCD8BH+/93t/+ZWSzDZHr49GKlmm+z6CGdvEhmeeoxSSsjduVPIdQS9MIhBwKW+nFMfsom2DvJ6I2ZuvDVCjrzEOmgO06IgIOBuJgzy6eu4eXU3EfU3U6FdkXUGBSkuimx53ZF+gPK13QMeHDlJYgx2dNN1a9b4fygAiTrVv7w6eh+Y+qvU6gJux8Peo+f5wg7nn/s3HO9lr3SI4c9m7YMn/q/moALwjSaRTyk+Hpksemb3UdMkjSAT5MRjiRcmo2K89hd0iVRPSMWugSL1LrRG4vVgb+fJOir1/bW53cjDjzZhm7NC4dhB1+GVugN7pnhtmcDujvYyBcU4ztkHYszt4CLD0J/zSRtRvJyfHnLb9CqiCTHDdzRXJdykflhOa4RtKjStoSJ0DyFg0Qo36p2cvO70mutuhKDI04fkQxgNHehYdgrq5sZbi2Yo4hn1Z3BExr58F8tJqdU9I+V7uOX8=}
